<h1>Privacy Policy</h1>

<p>THIS DOCUMENT SETS OUT HOW INFORMATION PROVIDED BY USERS OF THIS APP, VIBES, WILL BE PROTECTED AND USED BY VIBES, THE OWNER AND OPERATOR OF THIS APP. THIS DOCUMENT TOGETHER WITH THE EVENT PROMOTER TERMS AND CONDITIONS, THE GENERAL TERMS AND CONDITIONS AND ANY OTHER DOCUMENTS REFERRED TO IN ANY OF THE FORGOING DOCUMENTS SETS OUT THE TERMS AND CONDITIONS THAT GOVERN USE OF THIS WEBSITE BY ANY PERSON WHO VISITS OR USES IT.</p>
<p>On 25th May 2018, a new data privacy law known as the EU General Data Protection Regulation (or the "GDPR") becomes effective. The following privacy policy details how we process your personal data.</p>
<h3>1. General</h3>
<h5>1.1 This APP is owned and operated by Vibes SA Media trading as Vibes (the "APP"), a company registered in South Africa. Company registration number …………
    The provides box office and social networking services (collectively the "VSA Media Service").</h5>
<h5>1.2 Any person who visits or uses the APP agrees to be bound to this Privacy Policy (as amended from time to time). This Privacy Policy applies to all "personal data" as defined in the Data Protection Act 1998 and the Data Controller for the purpose of the same legislation shall be YPL.</h5>
<h5>1.3 This Privacy Policy only applies to information collected by VSA Media on the Site.</h5>
<h5>1.4 Any transmission of information to the Site is at the risk of the person doing so. Although VSA Media shall endeavour to protect information provided by users, it cannot guarantee that the information supplied will be protected against unauthorised access.</h5>
<h5>1.5 From time to time, VSA Media may contain links to other websites and services that are not owned or controlled by VSA Media. In these circumstances, VSA Media shall not be responsible for the privacy practices of those websites.</h5>
<h5>1.6 Any capitalised words used but not defined in this Privacy Policy shall have the same meaning as defined in either the Event Promoter Terms and Conditions or the General Terms and Conditions.</h5>
<h3>2. Information Collected</h3>
<h5>2.1 In order to use the VSA Media Service, a person may be required to provide certain information including but not limited to information which may be used to identify that person such as names, telephone numbers, residential/postal addresses and email addresses as well as financial information. This information may be provided to YPL and our Event Promoters using the platform to run an event.</h5>
<h5>2.2 In addition to the above, certain information is automatically transferred to the Site when the Site is used or visited. This includes but is not limited to Internet Protocol (IP) addresses, cookies and other connection information.</h5>
<h3>3. Use and Disclosure of Information</h3>
<h5>3.1 All information collected is used to improve and maintain the VSA Media Service. Some of examples include but are not limited to:</h5>
<h5>3.1.1 Using personally identifiable information (Personal Information) in order to prevent abuse of the Site;</h5>
<h5>3.1.2 Using financial information (Financial Information) to process orders and detect and prevent fraud;</h5>
<h5>3.1.3 Providing users with information regarding updates, promotions and recommendations;</h5>
<h5>3.1.4 Using automatic information to maintain and improve the Site and notifying users of any changes to the Site.</h5>
<h5>3.2 None of the information on the Site collected is sold to third parties. It is only used in the manner set out in this document, namely;</h5>
<h5>3.2.1 Information is always used in a manner which VSA Media believes is necessary to protect the integrity of the Site and the VSA Media;</h5>
<h5>3.2.2 Financial and Personal Information is never released to any third party unless it is necessary to do so in order to comply with the law, protect the Site, the VSA Media Service or other users of the Site;</h5>
<h5>3.2.3 Without prejudice to the forgoing or the remainder of this document, VSA Media in the event of a transfer of ownership of the Site, reserves the right to transfer any information it holds if so required as part of the transfer of ownership.</h5>
<h5>3.2.4 A person who provides Financial Information when using the VSA Media Service will be deemed to have given VSA Media express consent to use that Financial Information in any manner necessary in order to facilitate the delivery of the goods/services being purchased. This includes but is not limited to granting any relevant financial institutions access to the Financial Information for the purpose of facilitating payment.</h5>
<h5>3.2.5 The VSA Media Service includes a box office facility where VSA Media sells Tickets to Events on behalf of Event Promoters. The VSA Media Service also provides a platform from which the Event Promoter may manage the Event. In order to facilitate this, information collected on the Site may be shared between VSA Media and the Event Promoter.</h5>
<h5>3.2.6 In addition to paragraph 3.2.5 above, with consent, registered Users of the Site may be sent information about events, goods and/or services, which may be of interest to them. This information may be supplied by VSA Media. Any person who does not wish to receive information of this nature may leave the checkbox un-ticked prompted during registration or by sending an email with the word "unsubscribe" in the subject field to VSA Media at the following address:  unsubscribe@shoobs.com</h5>
<h5>3.2.7 Automatic Information refers to information such as IP addresses, information stored on cookies and any other information which can be used to determine how the Site and the VSA Media Service is being used and which is generated automatically. This is used to develop statistics and aggregate information about the number of people who visit the Site and use the VSA Media Service. This information is then used to customise the content and layout of the Site in order to improve the YPL Service. One of the ways this is achieved is by way of advertising. VSA Media may transfer Automatic Information to its advertising partners and other third parties. This information may be used to provide advertising, promotions and other products and services that may be of particular interest to registered Users. These advertising partners and third parties cannot access the YPL servers to obtain any Personal Information from there.</h5>
<h5>3.2.8 With your consent, we will contact you with information regarding our upcoming events, products or services. This contact may be through email, push and web notifications, SMS, or social media platforms.</h5>
<h5>3.2.9 We allow Event Promoters to contact users regarding event updates. This may be done by us on the behalf of the Event Promoter. If you have opted in to receive communications directly from the Event Promoter during the event booking process, your email address will be available to that Event Promoter. In some cases, Event Promoters may work with a third party to create an event on the platform which will enable them to see relevant information. To unsubscribe from an Event Promoter's database, please contact them directly. We are not responsible for the actions the Event Promoters or their third party affiliations.</h5>
<h5>3.2.10 Your information will provided to Event Promoters, for the purpose of event management and customer analytics and as further described in their Privacy Policy.</h5>
<h3>4. Cookies</h3>
<h5>4.1 When a computer accesses the Site, small files known as cookies, may be downloaded onto that computer automatically. These files contain information about how that computer is being used so that where it is used to access the Site frequently or where a particular feature of the Site is accessed frequently, VSA Media can obtain useful information on how to improve the Site and the VSA Media Service.</h5>
<h5>4.2 Cookies can be disabled. Users are advised to consult the "help" function on this matter.</h5>
<h3>5. Security and confidentiality</h3>
<h5>5.1 VSA Media has installed secure-server software which encrypts all Personal Information and Financial Information including credit and debit card numbers. The encryption process takes the characters entered on the Site and converts them into bits of code that are then securely transmitted over the Internet. This is done using 128-bit Secure Socket Layer certificates. As a result, no cardholder information is passed unencrypted. Messages sent to the VSA Media servers are signed using MD5 hashing to further protect the information</h5>
<h3>6. Transfer of data</h3>
<h5>In order to fulfil our services, VSA Media may need to transfer your Personal Data outside of the country from which it was originally provided. This may be third parties (e.g such as server providers) that we work with who may be located in jurisdictions outside the EEA, Switzerland and the UK which have no data protection laws or laws that are less strict compared with those in Europe.
Whenever we transfer Personal Data outside of the EEA, Switzerland or the UK, we take legally required steps to make sure that appropriate safeguards are in place to protect your Personal Data.</h5>
